/**
 * AI auto-reply extension plugin — com memória de conversa.
 *
 * Hooks inbound messages and replies with a response generated by a local, open-source LLM
 * served by Ollama (default: qwen2.5:7b-instruct). Mantém um histórico por conversa (chatId)
 * persistido via context.storage, de modo que o modelo recebe os últimos turnos e responde
 * com contexto — sem se repetir e lembrando do que já foi dito (inclusive após reiniciar).
 * Falls back to a static message if the model is unreachable. Responde apenas a mensagens
 * diretas (1:1), nunca grupos nem mensagens enviadas pela própria conta.
 *
 * Config via env (with defaults):
 *   OLLAMA_URL          base URL of the Ollama server (default http://host.docker.internal:11434)
 *   OLLAMA_MODEL        model tag to use            (default qwen2.5:7b-instruct)
 *   OLLAMA_TIMEOUT_MS   per-request timeout in ms   (default 30000)
 *   AI_HISTORY_TURNS    nº de turnos (par user+bot) lembrados por conversa (default 8)
 *   AI_SYSTEM_PROMPT    system persona/instructions (default: friendly pt-BR WhatsApp assistant)
 */
import { PluginContext, IPlugin } from '../../../core/plugins';
import { HookContext, HookResult } from '../../../core/hooks';
import { IncomingMessage } from '../../../engine/interfaces/whatsapp-engine.interface';

const OLLAMA_URL = process.env.OLLAMA_URL ?? 'http://host.docker.internal:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL ?? 'qwen2.5:7b-instruct';
const TIMEOUT_MS = Number(process.env.OLLAMA_TIMEOUT_MS ?? 30000);
const HISTORY_TURNS = Number(process.env.AI_HISTORY_TURNS ?? 8);
const SYSTEM_PROMPT =
  process.env.AI_SYSTEM_PROMPT ??
  'Você é uma assistente de atendimento via WhatsApp, simpática e prestativa. ' +
    'Responda de forma curta, clara e natural, em português brasileiro. Não use markdown.';
const FALLBACK = 'Desculpe, estou com dificuldade para responder agora. Pode tentar novamente em instantes?';

type ChatTurn = { role: 'user' | 'assistant'; content: string };

export class AutoReplyPlugin implements IPlugin {
  onEnable(context: PluginContext): Promise<void> {
    context.registerHook('message:received', ctx => this.onMessage(context, ctx as HookContext<IncomingMessage>));
    context.logger.log(`AI auto-reply enabled (model=${OLLAMA_MODEL}, memória=${HISTORY_TURNS} turnos, url=${OLLAMA_URL})`);
    return Promise.resolve();
  }

  /** Per-chat history persisted under storage key `hist-<chatId>`. */
  private historyKey(chatId: string): string {
    // JID chars (@ : . -) são permitidos como nome de arquivo; trocamos apenas o que poderia escapar.
    return `hist-${chatId.replace(/[^a-zA-Z0-9@:._-]/g, '_')}`;
  }

  private async loadHistory(context: PluginContext, chatId: string): Promise<ChatTurn[]> {
    const saved = await context.storage.get<ChatTurn[]>(this.historyKey(chatId));
    return Array.isArray(saved) ? saved : [];
  }

  private async saveHistory(context: PluginContext, chatId: string, history: ChatTurn[]): Promise<void> {
    // Mantém só os últimos N turnos (N*2 mensagens) para não estourar o contexto do modelo.
    const trimmed = history.slice(-HISTORY_TURNS * 2);
    await context.storage.set(this.historyKey(chatId), trimmed);
  }

  /** Ask the local Ollama model for a reply, given the conversation so far. */
  private async generate(history: ChatTurn[], userText: string): Promise<string> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      const res = await fetch(`${OLLAMA_URL}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: OLLAMA_MODEL,
          stream: false,
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            ...history,
            { role: 'user', content: userText },
          ],
          options: { temperature: 0.7, num_predict: 320 },
        }),
        signal: controller.signal,
      });
      if (!res.ok) {
        throw new Error(`Ollama HTTP ${res.status}`);
      }
      const data = (await res.json()) as { message?: { content?: string } };
      const text = data.message?.content?.trim();
      if (!text) {
        throw new Error('empty AI response');
      }
      return text;
    } finally {
      clearTimeout(timer);
    }
  }

  private async onMessage(context: PluginContext, ctx: HookContext<IncomingMessage>): Promise<HookResult> {
    const message = ctx.data;

    // Reply only to inbound, non-group, engine-originated messages; never to our own sends.
    if (ctx.source !== 'Engine' || !ctx.sessionId || message.fromMe || message.isGroup) {
      return { continue: true };
    }

    const body = (message.body ?? '').trim();
    if (!body) {
      // Nothing textual to answer (media/sticker/etc.) — leave it alone.
      return { continue: true };
    }

    const chatId = message.chatId;
    try {
      const history = await this.loadHistory(context, chatId);

      let reply: string;
      try {
        reply = await this.generate(history, body);
      } catch (aiErr) {
        context.logger.warn('AI generation failed; sending fallback', { error: String(aiErr) });
        reply = FALLBACK;
        await context.messages.reply(ctx.sessionId, chatId, message.id, reply);
        return { continue: true }; // não grava fallback no histórico
      }

      await context.messages.reply(ctx.sessionId, chatId, message.id, reply);

      // Persiste o turno (pergunta + resposta) para dar memória/contexto às próximas mensagens.
      history.push({ role: 'user', content: body }, { role: 'assistant', content: reply });
      await this.saveHistory(context, chatId, history);
    } catch (error) {
      context.logger.error('Auto-reply failed', error);
    }

    // Keep the inbound message in history + webhooks + ws (do not swallow).
    return { continue: true };
  }
}

export default AutoReplyPlugin;
