/**
 * AI auto-reply extension plugin.
 *
 * Hooks inbound messages and replies with a response generated by a local, open-source LLM
 * served by Ollama (default: qwen2.5:3b-instruct). Falls back to a static message if the model
 * is unreachable. Replies only to inbound, non-group, engine-originated text messages.
 *
 * Config via env (with defaults):
 *   OLLAMA_URL          base URL of the Ollama server (default http://host.docker.internal:11434)
 *   OLLAMA_MODEL        model tag to use            (default qwen2.5:3b-instruct)
 *   OLLAMA_TIMEOUT_MS   per-request timeout in ms   (default 30000)
 *   AI_SYSTEM_PROMPT    system persona/instructions (default: friendly pt-BR WhatsApp assistant)
 */
import { PluginContext, IPlugin } from '../../../core/plugins';
import { HookContext, HookResult } from '../../../core/hooks';
import { IncomingMessage } from '../../../engine/interfaces/whatsapp-engine.interface';

const OLLAMA_URL = process.env.OLLAMA_URL ?? 'http://host.docker.internal:11434';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL ?? 'qwen2.5:3b-instruct';
const TIMEOUT_MS = Number(process.env.OLLAMA_TIMEOUT_MS ?? 30000);
const SYSTEM_PROMPT =
  process.env.AI_SYSTEM_PROMPT ??
  'Você é um assistente de atendimento via WhatsApp, simpático e prestativo. ' +
    'Responda de forma curta, clara e natural, em português brasileiro. Não use markdown nem listas longas.';
const FALLBACK = 'Desculpe, estou com dificuldade para responder agora. Pode tentar novamente em instantes?';

export class AutoReplyPlugin implements IPlugin {
  onEnable(context: PluginContext): Promise<void> {
    context.registerHook('message:received', ctx => this.onMessage(context, ctx as HookContext<IncomingMessage>));
    context.logger.log(`AI auto-reply enabled (model=${OLLAMA_MODEL}, url=${OLLAMA_URL})`);
    return Promise.resolve();
  }

  /** Ask the local Ollama model for a reply. Throws on timeout / HTTP error / empty output. */
  private async generate(prompt: string): Promise<string> {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
    try {
      const res = await fetch(`${OLLAMA_URL}/api/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: OLLAMA_MODEL,
          stream: false,
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: prompt },
          ],
          options: { temperature: 0.7, num_predict: 256 },
        }),
        signal: controller.signal,
      });
      if (!res.ok) {
        throw new Error(`Ollama HTTP ${res.status}`);
      }
      const data = (await res.json()) as { message?: { content?: string } };
      const text = data.message?.content?.trim();
      if (!text) {
        throw new Error('empty AI response');
      }
      return text;
    } finally {
      clearTimeout(timer);
    }
  }

  private async onMessage(context: PluginContext, ctx: HookContext<IncomingMessage>): Promise<HookResult> {
    const message = ctx.data;

    // Reply only to inbound, non-group, engine-originated messages; never to our own sends.
    if (ctx.source !== 'Engine' || !ctx.sessionId || message.fromMe || message.isGroup) {
      return { continue: true };
    }

    const body = (message.body ?? '').trim();
    if (!body) {
      // Nothing textual to answer (media/sticker/etc.) — leave it alone.
      return { continue: true };
    }

    try {
      let reply: string;
      try {
        reply = await this.generate(body);
      } catch (aiErr) {
        context.logger.warn('AI generation failed; sending fallback', { error: String(aiErr) });
        reply = FALLBACK;
      }
      await context.messages.reply(ctx.sessionId, message.chatId, message.id, reply);
    } catch (error) {
      context.logger.error('Auto-reply failed', error);
    }

    // Keep the inbound message in history + webhooks + ws (do not swallow).
    return { continue: true };
  }
}

export default AutoReplyPlugin;
